package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-macosx-x86_64/jdk8u66/4988/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 6, 2015 4:10:32 PM PDT
*/


/**
    * DynSequence objects support the manipulation of IDL sequences.
    */
public interface DynSequence extends DynSequenceOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynSequence
