package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/Interceptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-macosx-x86_64/jdk8u66/4988/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, October 6, 2015 4:10:33 PM PDT
*/


/**
   * All Portable Interceptors implement Interceptor.
   */
public interface Interceptor extends InterceptorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interceptor
